/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antidebug_demo08_usendk */

#ifndef _Included_com_antidebug_demo08_usendk
#define _Included_com_antidebug_demo08_usendk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antidebug_demo08_usendk
 * Method:    ptracecheck
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_antidebug_demo08_usendk_ptracecheck
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
