/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antidebug_demo02_usejni */

#ifndef _Included_com_antidebug_demo02_usejni
#define _Included_com_antidebug_demo02_usejni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antidebug_demo02_usejni
 * Method:    antirpocess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_antidebug_demo02_usejni_antirpocess
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
