/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antidebug_demo01_uselib */

#ifndef _Included_com_antidebug_demo01_uselib
#define _Included_com_antidebug_demo01_uselib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antidebug_demo01_uselib
 * Method:    antoida
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_antidebug_demo01_uselib_antoida(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
