/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antidebug_demo5_ndkuse */

#ifndef _Included_com_antidebug_demo5_ndkuse
#define _Included_com_antidebug_demo5_ndkuse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antidebug_demo5_ndkuse
 * Method:    checktaskcounts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_antidebug_demo5_ndkuse_checktaskcounts
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
